#!/usr/bin/env bash
# deploy/selfhost/install.sh
# One-liner installer for agentic-delegator (selfhost edition).
# Usage: curl -fsSL https://<your-releases>/install.sh | sudo bash
set -euo pipefail

VERSION="${AGENTIC_VERSION:-latest}"
# AGENTIC_REPO defaults to <owner>/agentic-delegator as a placeholder.
# The operator running this installer must override it via:
#   AGENTIC_REPO=myorg/agentic-delegator bash install.sh
REPO="${AGENTIC_REPO:-<owner>/agentic-delegator}"
PREFIX="${AGENTIC_PREFIX:-/usr/local}"
USER_NAME="agentic-delegator"
HOME_DIR="/var/lib/agentic-delegator"
CONFIG_DIR="/etc/agentic-delegator"

require() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1" >&2; exit 1; }; }
require curl
require tar
require docker

if [ "$EUID" -ne 0 ]; then
  echo "must be run as root (use sudo)" >&2
  exit 1
fi

uname_s=$(uname -s | tr A-Z a-z)
uname_m=$(uname -m)
case "$uname_m" in
  x86_64|amd64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) echo "unsupported arch: $uname_m"; exit 2 ;;
esac

# 1. Create unprivileged user
if ! id "$USER_NAME" >/dev/null 2>&1; then
  useradd --system --home-dir "$HOME_DIR" --create-home --shell /usr/sbin/nologin "$USER_NAME"
fi
usermod -aG docker "$USER_NAME"

# 2. Download release tarball
url="https://github.com/${REPO}/releases/${VERSION}/download/agentic-delegator-${uname_s}-${ARCH}.tar.gz"
if [ "$VERSION" = "latest" ]; then
  url="https://github.com/${REPO}/releases/latest/download/agentic-delegator-${uname_s}-${ARCH}.tar.gz"
fi
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

echo "Downloading $url"
curl -fsSL "$url" | tar -xz -C "$tmp"

install -m 755 "$tmp/agentic-delegator" "$PREFIX/bin/agentic-delegator"

# 3. Config dir
mkdir -p "$CONFIG_DIR"
if [ ! -f "$CONFIG_DIR/env" ]; then
  master_key=$(openssl rand -hex 32)
  pg_password=$(openssl rand -hex 16)
  cat > "$CONFIG_DIR/env" <<EOF
# Generated by agentic-delegator install.sh
AGENTIC_HTTP_BIND=127.0.0.1:8787
AGENTIC_MASTER_KEY=${master_key}
DELEGATOR_DSN=postgres://delegator:${pg_password}@127.0.0.1:5432/delegator?sslmode=disable
AGENTIC_RUNNER_IMAGE=agentic-delegator-runner:dev
POSTGRES_PASSWORD=${pg_password}
EOF
  chmod 600 "$CONFIG_DIR/env"
  chown "$USER_NAME":"$USER_NAME" "$CONFIG_DIR/env"
fi

# 4. systemd unit
install -m 644 "$tmp/agentic-delegator.service" /etc/systemd/system/agentic-delegator.service
systemctl daemon-reload

# 5. Postgres
install -m 644 "$tmp/docker-compose.postgres.yml" "$CONFIG_DIR/docker-compose.postgres.yml"
( cd "$CONFIG_DIR" && set -a; . ./env; set +a; docker compose -f docker-compose.postgres.yml up -d )

# 6. Migrate + init
sudo -u "$USER_NAME" env $(grep -v '^#' "$CONFIG_DIR/env" | xargs) "$PREFIX/bin/agentic-delegator" migrate up
sudo -u "$USER_NAME" env $(grep -v '^#' "$CONFIG_DIR/env" | xargs) "$PREFIX/bin/agentic-delegator" init

# 7. Start
systemctl enable --now agentic-delegator

cat <<EOF

==========================================================
agentic-delegator installed.
Service: systemctl status agentic-delegator
Config:  $CONFIG_DIR/env
Logs:    journalctl -u agentic-delegator -f
URL:     http://127.0.0.1:8787 (consider Caddy in front)

Next:
  1) Open http://127.0.0.1:8787/admin/setup and paste your GitHub PAT.
  2) Open /settings and paste your Anthropic API key.
  3) Install skill/delegate.md into Claude Code.
==========================================================
EOF
